### ISSUE TITLE
Error: Untyped decorator (@typeguard) makes function "add_two" untyped [misc]

### ISSUE THREAD

**Issue by a-t-0** [agronholm/typeguard#308]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Typeguard version

2.13,3 - 3.0.0b1 - 3.0.0b2 - 3.0.0rc1 - 3.0.0rc2

### Python version

3.10

## Context

While using [typeguard](https://github.com/agronholm/typeguard/issues/60) on a project with `mypy`, I've encountered the error:

```
src/pythontemplate/adder.py:6: error: Untyped decorator makes function "add_two" untyped  [misc]
```
on the following example code:
```py
"""Example python file with a function."""

from typeguard import typechecked


@typechecked
def add_two(*, x: int) -> int:
    """Adds a value to an incoming number."""
    return x + 2

```

After looking at [this](https://stackoverflow.com/a/65641392/7437143) answer, it seems one can resolve this error message by manually adding a typing for the `@typechecked` function/decorator.

## Issue
 1. I did not quite determine what the typing should be for the `@typeguard` decorator.
 2. This decorator is in each `python` file in the project, so adding the typing for that decorator in each file, or even an import to a separate file with that typing, would be quite a bit of duplicate code and/or boilerplate code.  
2. This decorator is specifically for typechecking, so I would expect there may be a more elegant fashion to resolve this issue. 

## Question
How can one ensure the `@typeguard` decorator is typed?

## Notes
I tried the latest 5 `typeguard` versions with `pip`, and verified they were installed. With  `pip list` which returned: 
```
typeguard          3.0.0rc2
```

### How can we reproduce the bug?

```
git clone https://github.com/HiveMinds/python-template.git
cd python-template
pre-commit install
#  conda env create --file environment.yml
# conda activate pythontemplate
pre-commit run --all
```
Which outputs the error above.

**Comment by agronholm** [comment]
But the decorator IS typed:
```
@overload
def typechecked() -> Callable[[T_CallableOrType], T_CallableOrType]:
    ...


@overload
def typechecked(target: T_CallableOrType) -> T_CallableOrType:
    ...


def typechecked(target: T_CallableOrType | None = None) -> Any:
```

**Comment by agronholm** [comment]
Ah, could the problem be that it returns `Any`?

**Comment by a-t-0** [comment]
> 

Thank you for the suggestion. Based on the following actions and observations I would conclude/expect that is not (likely to be) the case:

## Approach I
1. I looked up the typeguard pip package in my conda environment, and found the `_decorators` file in: `~./miniconda/envs/pythontemplate/lib/python3.10/site-packages/typeguard/src/typeguard/_decorators.py`.
2. Changed:
```py
def typechecked(target: T_CallableOrType | None = None) -> Any:
```
to:
```py
def typechecked(target: T_CallableOrType | None = None) -> int:
```
3. Than ran the `pre-commit run all` command again.
However, it is possible that conda actually uses some compiled package instead of those source files, so just to exclude that option, I also compiled your head main branch after modification and installed it locally. (See approach II).

## Approach II
1. I cloned your repository.
3. Changed:
```py
```
to:
```py
```
then build the package with:
```bash
python -m build
```
5. Then verified it was installed with: `pip list` which returned:
```
typeguard               3.0.0rc2.post0+dirty /home/name/git/typeguard
```
6. Closed the terminal, opened it again, activated the `pythontemplate` conda envirionment, verified the `typeguard` pip package was the latest/modified one.
3. Than ran the `pre-commit run all` command again.

## Output
The output remains the same bug as described above.

**Comment by agronholm** [comment]
I looked at your pre-commit config and it looks like you forgot to install typeguard as a dependency for mypy.

**Comment by a-t-0** [comment]
> I looked at your pre-commit config and it looks like you forgot to install typeguard as a dependency for mypy.
Thank you! That was indeed the issue. I was unaware that mypy did not look for typeguard in the conda environment in which the `pre-commit run --all` command is executed. So after changing:

```yml
 - repo: https://github.com/pre-commit/mirrors-
   rev: v1.1.1
   hooks:
    - id: mypy
      # args: ["--disallow-untyped-calls", "--disallow-untyped-defs"]
      args: ["--strict"]
```
to:
```yml
 - repo: https://github.com/pre-commit/mirrors-mypy
### - repo: https://github.com/a-t-0/mypy
   rev: v1.1.1
   hooks:
    - id: mypy
      # args: ["--disallow-untyped-calls", "--disallow-untyped-defs"]
      args: ["--strict"]
      additional_dependencies:
            - typeguard
```
The issue was resolved!
